### ISSUE TITLE
HW1 MADE |  possible flaws in solution implementaiotn.

### ISSUE THREAD

**Issue by diff7** [rll/deepul#4]
Hi, 
first of all thank you for the course and provided solutions. 

There are maybe a few flaws in MADE implementation but I can be wrong.

```python
for l in range(num_hidden):
            self.m[l] = np.random.randint(
                self.m[l - 1].min(), self.nin - 1, size=self.hidden_sizes[l]
            )
```

When you initialize random numbers for masks it seems better to use permutation, otherwise we may zero  more  than we need. Let's say with a very low chance  we can get the next m with all the same numbers.  

Also, as I understand size of unique numbers in m for all m should be not smaller than 'nin -1', therefore len(m) should not be less than  'nin -1'. Maybe better to add some assertion for it.

Again, 
I may be wrong and thank you for your great work.

**Comment by wilson1yan** [comment]
Yes, there's definitely a chance for a bad random sample, but permutation wouldn't exactly work since we could have a MADE setup with an input dimension 10, and say, a hidden layer of size 1000. In this case, we would need to sample units with repetitive autoregressive groups.

I think in practice, since we usually sample a small number of masks (i.e. 1 - 4), it's unlikely to run into a really bad masking scheme. If its a large concern, we could probably implement some naive check and re-sample if needed.

**Comment by diff7** [comment]
Well, it makes sense. Thank you!
